version: "3.9"

services:
  app:
    build: .
    container_name: linkingtuna
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
